version: '3'
volumes:
  db-volume:
  maildir: {}

services:
  php:
    container_name: web
    build: ./php
    ports:
      - 80:80
    #hostname: localhost
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./logs/maillog:/usr/local/etc/mail
    networks:
      - br0

  # mailhogの設定を追記
  mailhog:
    container_name: mailhog
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
    networks:
      - br0

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db_table
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    tty: true
    networks:
      - br0

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=test
      - PMA_PASSWORD=test
      - MEMORY_LIMIT=256M
      - UPLOAD_LIMIT=128M
    ports:
      - 4090:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    networks:
      - br0

networks:
  br0:
    driver: bridge
